### ISSUE TITLE
Incompatibility with spacy>=0.100

### ISSUE THREAD

**Issue by abelsonlive** [cemoody/lda2vec#10]
`spacy` [deprecated](https://github.com/spacy-io/spaCy/blob/master/spacy/en/__init__.py#L36) the use of the [LOCAL_DATA_DIR](https://github.com/cemoody/lda2vec/blob/master/lda2vec/preprocess.py#L64) variable after version `0.100`. The `spacy` [source](https://github.com/spacy-io/spaCy/blob/master/spacy/language.py#L205) indicates that you can now call a `Language` class without a `data_dir`.

Using `spacy==0.100.5`, I was gettting the following error:
```
Traceback (most recent call last):
  File "cluster_articles_lda2vec.py", line 35, in <module>
    tokens, vocab = preprocess.tokenize(texts, max_length, tag=False, parse=False, entity=False)
  File "/Users/brianabelson/.virtualenvs/similar/lib/python2.7/site-packages/lda2vec/preprocess.py", line 65, in tokenize
    nlp = English(data_dir=data_dir)
  File "/Users/brianabelson/.virtualenvs/similar/lib/python2.7/site-packages/spacy/language.py", line 231, in __init__
    vocab = self.default_vocab(package)
  File "/Users/brianabelson/.virtualenvs/similar/lib/python2.7/site-packages/spacy/language.py", line 165, in default_vocab
    return Vocab.from_package(package, get_lex_attr=get_lex_attr)
  File "spacy/vocab.pyx", line 65, in spacy.vocab.Vocab.from_package (spacy/vocab.cpp:3592)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/brianabelson/.virtualenvs/similar/lib/python2.7/site-packages/sputnik/package_stub.py", line 68, in open
    raise default(self.file_path(*path_parts))
IOError: ~/.virtualenvs/similar/lib/python2.7/site-packages/spacy/en/data/vocab/strings.json
```

This is related to #8 and #2.

**Comment by syllog1sm** [comment]
@hp could we help out a little here? It's not obvious to me what the incompatibility is. Is it just that the model needs to be retrained...?

I know you've got another ticket open about removing the dependency on spaCy. And it's true that it's maybe a little heavy-weight for the use you're making of it here. But v0.100 includes an easy data pack for the GloVe vectors, and it loads about 10x quicker than the version you're using.

**Comment by samcarlos** [comment]
I'm still getting this error:

>>> tokens, vocab = preprocess.tokenize(texts, max_length, tag=False,
...                                     parse=False, entity=False)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "build/bdist.macosx-10.5-x86_64/egg/lda2vec/preprocess.py", line 65, in tokenize
  File "//anaconda/lib/python2.7/site-packages/spacy/language.py", line 231, in __init__
    vocab = self.default_vocab(package)
  File "//anaconda/lib/python2.7/site-packages/spacy/language.py", line 165, in default_vocab
    return Vocab.from_package(package, get_lex_attr=get_lex_attr)
  File "spacy/vocab.pyx", line 65, in spacy.vocab.Vocab.from_package (spacy/vocab.cpp:3592)
  File "//anaconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "//anaconda/lib/python2.7/site-packages/sputnik/package_stub.py", line 67, in open
    raise default(self.file_path(*path_parts))
IOError: //anaconda/lib/python2.7/site-packages/spacy/en/data/vocab/strings.json

Any suggestions? 

Thanks,
Sam

**Comment by cemoody** [comment]
I've removed the references to LOCAL_DATA_DIR... should be much better now. Thanks for bringing this up!
