### ISSUE TITLE
error with  preprocess.py

### ISSUE THREAD

**Issue by enhiko** [cemoody/lda2vec#45]
## hello i have this error in preprocess.py

> python3 preprocess.py 
> Traceback (most recent call last):
>   File "preprocess.py", line 8, in <module>
>     from lda2vec import preprocess, Corpus
>   File "/usr/local/lib/python3.5/dist-packages/lda2vec-0.1-py3.5.egg/lda2vec/**init**.py", line 1, in <module>
> ImportError: No module named 'dirichlet_likelihood'

but there is no module named 'dirichlet_likehood' in https://pypi.python.org/pypi .

**Comment by radekrepo** [comment]
What operating system do you use with lda2vec?

Myself I don't know how could I help you. I can only say that I had a lot of problems like that when I used my computer that runs on Windows. I ended up resorting to expert help in my office because it was too complex for my skill level

**Comment by agtsai-i** [comment]
Odd, that file is referencing [dirichlet_likelihood](https://github.com/cemoody/lda2vec/blob/master/lda2vec/dirichlet_likelihood.py) which resides in the same folder. Maybe something weird is going on with your search path? Try:

```
import sys
print(sys.path)
```

And see if it makes sense.

**Comment by chenjun0210** [comment]
when i run preprocess.py 
Traceback (most recent call last):
  File "preprocess.py", line 56, in <module>
    vectors, s, f = corpus.compact_word_vectors(vocab, filename=fn_wordvc)
  File "build/bdist.linux-x86_64/egg/lda2vec/corpus.py", line 575, in compact_word_vectors
NameError: global name 'damerau_levenshtein_distance_withNPArray' is not defined

**Comment by crawfordcomeaux** [comment]
@chenjun0210 Your issue might be fixed via #46. Apply the changes to corpus.py & also confirm you have the packages mentioned in the PR's first comment.

**Comment by mostafa-mahmoud** [comment]
The problem for this issue, is that (seems you're using python3) in python3 it should be imported using
`import lda2vec.dirichlet_likelihood`
and not
`import dirichlet_likelihood`
Uninstalling lda2vec, and making this change for all imported modules in __init__.py fixed the problem.

**Comment by MaisHanoon** [comment]
In addition to updating the import , I had to append the below to ~./bash_profile:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
And then run:
$ source ~/.bash_profile

**Comment by iamtechaddict** [comment]
Even I'm facing the same issue I'm installed using setup.py and I'm getting this error

>>> import lda2vec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rkumar3\AppData\Local\Continuum\anaconda3\lib\site-packages\lda2vec-0.1-py3.6.egg\lda2vec\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'dirichlet_likelihood'

**Comment by starry9t** [comment]
> In addition to updating the import , I had to append the below to ~./bash_profile:
> 
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> And then run:
> $ source ~/.bash_profile

tried this but not working.

**Comment by sudheernaidu53** [comment]
hi,
I have faced similar problems too, and there were many files missing from lda2vec after installation using pip install. I was able to move the files around from git to local folder where lda2vec has been installed but I am not able to find this one function called 'move'. Can anyone help me
from lda2vec.utils import move
ImportError: cannot import name 'move' from 'lda2vec.utils' (C:\Users\Sudheera\Anaconda3\lib\site-packages\lda2vec\utils.py

**Comment by fathia-ghribi** [comment]
when i run 
from lda2vec import preprocess, Corpus
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
try:
    import seaborn
except:
    pass
/***********/
ImportError: cannot import name 'preprocess' from 'lda2vec' (C:\Users\fathi\anaconda\lib\site-packages\lda2vec\__init__.py)
someone help me for solve this error ??
thnks

**Comment by fathia-ghribi** [comment]
good evening !
I'm running the lda2vec algorithm with Hacker_new, when I run the module preprocess.py I had the following problem: 
`File "C:\Users\fathi\anaconda\envs\tf\lib\site-packages\lda2vec-0.1-py3.7.egg\lda2vec\preprocess.py", line 49
    """ Uses spaCy to quickly tokenize text and return an array
                                                              ^
IndentationError: unindent does not match any outer indentation level
How to fix this error ??
